# Generated by Django 4.2.2 on 2024-03-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='category',
            field=models.CharField(default='食費', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='money',
            name='use_date',
            field=models.DateField(verbose_name='日付'),
        ),
    ]
