# Generated by Django 4.2.2 on 2024-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_money_category_alter_money_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='use_date',
            field=models.DateTimeField(verbose_name='日付'),
        ),
    ]
