# Generated by Django 4.2.2 on 2024-03-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_alter_incomeitem_name_alter_paymentorigitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-month',)},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='incomeitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='incomeorigitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='paymentcategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='paymentitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='paymentorigitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='income',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.incomeitem', verbose_name='収入項目'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.incomeorigitem', verbose_name='ユーザー設定収入項目'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='収入カテゴリ'),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='収入項目'),
        ),
        migrations.AlterField(
            model_name='incomeorigitem',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='ユーザー設定収入項目'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='支出カテゴリ'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='支出項目'),
        ),
        migrations.AlterField(
            model_name='paymentorigitem',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='ユーザー設定支出項目'),
        ),
    ]
