# Generated by Django 4.2.2 on 2024-03-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_family_remove_user_last_name_user_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='家名'),
        ),
    ]
