# Generated by Django 4.2.2 on 2024-03-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_family_family_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ('id',)},
        ),
    ]
