# Generated by Django 4.2.2 on 2024-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_family_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='家名'),
        ),
    ]
