# Generated by Django 4.2.2 on 2024-03-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_family_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='家名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.family', verbose_name='家名'),
        ),
    ]
