# Generated by Django 4.2.2 on 2024-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_incomeorigitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeitem',
            name='name',
            field=models.CharField(max_length=32, verbose_name='収入項目'),
        ),
        migrations.AlterField(
            model_name='paymentorigitem',
            name='name',
            field=models.CharField(max_length=32, verbose_name='ユーザー設定支出項目'),
        ),
    ]
